--- #YAML:1.0
name:                Rose-DB-Object
version:             0.7664
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Bit::Vector::Overload:         0
    Clone:                         0.2
    Cwd:                           0
    DateTime:                      0
    DBI:                           1.4
    File::Path:                    0
    File::Spec:                    0
    List::MoreUtils:               0
    Math::BigInt:                  1.77
    Rose::DateTime::Util:          0.532
    Rose::DB:                      0.737
    Rose::Object:                  0.84
    Scalar::Util:                  0
    Test::More:                    0
    Time::Clock:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
