--- #YAML:1.0
name:                Rose-DB-Object
version:             0.7711
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Bit::Vector:                   0
    Clone:                         0.20
    Cwd:                           0
    Data::Dumper:                  2.121
    DateTime:                      0
    DBI:                           1.40
    File::Path:                    0
    File::Spec:                    0
    List::MoreUtils:               0
    Math::BigInt:                  1.77
    Rose::DateTime::Util:          0.532
    Rose::DB:                      0.745
    Rose::Object:                  0.852
    Scalar::Util:                  0
    Test::More:                    0
    Time::Clock:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
