--- #YAML:1.0
name:               Rose-DB-Object
version:            0.793
abstract:           Extensible, high performance object-relational mapper (ORM).
author:
    - John Siracusa <siracusa@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bit::Vector:          0
    Clone:                0.29
    Cwd:                  0
    Data::Dumper:         2.121
    DateTime:             0
    DBI:                  1.40
    File::Path:           0
    File::Spec:           0
    List::MoreUtils:      0
    Math::BigInt:         1.77
    perl:                 5.006000
    Rose::DateTime::Util:  0.532
    Rose::DB:             0.762
    Rose::Object:         0.854
    Scalar::Util:         0
    Test::More:           0
    Time::Clock:          1.00
resources:
    bugtracker:   http://rt.cpan.org/NoAuth/Bugs.html?Dist=Rose-DB-Object
    homepage:     http://rose.googlecode.com/
    license:      http://dev.perl.org/licenses/
    MailingList:  http://groups.google.com/group/rose-db-object
    repository:   http://rose.googlecode.com/svn/trunk/modules/Rose-DB-Object
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
